// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's TrainyLab profile: name, goal, level, biometrics, and whether they are a student with a personal trainer or a trainer themselves.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: profile, error } = await supabase.from("profiles").select(
      "full_name, email, sex, birth_date, height, weight, goal, experience_level, training_days, training_location, has_injury, injury_description, has_personal, personal_trainer_id"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const { data: trainer } = await supabase.from("personal_trainers").select("id, full_name, personal_code").eq("user_id", ctx.getUserId()).maybeSingle();
    const payload = { profile, is_personal_trainer: !!trainer, trainer_profile: trainer ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-my-students.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_my_students_default = defineTool2({
  name: "list_my_students",
  title: "List my students",
  description: "For a signed-in personal trainer: list the students linked to them, with name, email, goal, level and their current workout plan status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: trainer, error: trainerError } = await supabase.from("personal_trainers").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (trainerError) return { content: [{ type: "text", text: trainerError.message }], isError: true };
    if (!trainer) {
      return {
        content: [{ type: "text", text: "This account is not a personal trainer, so it has no students." }],
        isError: true
      };
    }
    const { data: students, error } = await supabase.from("profiles").select("user_id, full_name, email, goal, experience_level, training_location, created_at").eq("personal_trainer_id", trainer.id).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ids = (students ?? []).map((s) => s.user_id);
    const plans = ids.length ? (await supabase.from("workout_plans").select("user_id, id, status, division, expires_at, created_at").in("user_id", ids).order("created_at", { ascending: false })).data ?? [] : [];
    const items = (students ?? []).map((s) => ({
      ...s,
      latest_plan: plans.find((p) => p.user_id === s.user_id) ?? null
    }));
    const payload = { count: items.length, items };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-workout-plan.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var get_workout_plan_default = defineTool3({
  name: "get_workout_plan",
  title: "Get workout plan",
  description: "Return a full workout plan with its training days and exercises (sets, reps, notes). Defaults to the signed-in user's active plan; a personal trainer can pass a student's user id, or any accessible plan id.",
  inputSchema: {
    student_user_id: z.string().uuid().optional().describe("User id of a student. Trainers only; omit to read your own plan."),
    plan_id: z.string().uuid().optional().describe("Specific workout plan id."),
    status: z.string().optional().describe("Filter by plan status, e.g. 'ativa' or 'aguardando_revisao_personal'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ student_user_id, plan_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("workout_plans").select(
      "id, user_id, status, objective, division, level, days_per_week, training_location, validity_months, expires_at, created_at, updated_at, workout_days(id, name, muscle_groups, sort_order, workout_exercises(id, exercise_name, sets, reps, notes, image_url, sort_order))"
    ).order("created_at", { ascending: false }).limit(1);
    if (plan_id) query = query.eq("id", plan_id);
    else query = query.eq("user_id", student_user_id ?? ctx.getUserId());
    if (status) query = query.eq("status", status);
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "No workout plan found (or you don't have access to it)." }],
        isError: true
      };
    }
    const plan = {
      ...data,
      workout_days: [...data.workout_days ?? []].sort((a, b) => a.sort_order - b.sort_order).map((day) => ({
        ...day,
        workout_exercises: [...day.workout_exercises ?? []].sort(
          (a, b) => a.sort_order - b.sort_order
        )
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(plan, null, 2) }],
      structuredContent: { plan }
    };
  }
});

// src/lib/mcp/tools/search-exercises.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var search_exercises_default = defineTool4({
  name: "search_exercises",
  title: "Search exercise catalog",
  description: "Search TrainyLab's exercise catalog by name, muscle group, equipment or level. Useful to pick exercises when planning or adapting a workout.",
  inputSchema: {
    query: z2.string().trim().optional().describe("Text to match against the exercise name."),
    muscle_group: z2.string().trim().optional().describe("Muscle group filter, e.g. 'peito'."),
    equipment_type: z2.string().trim().optional().describe("Equipment filter, e.g. 'academia' or 'casa'."),
    level: z2.string().trim().optional().describe("Suggested level filter, e.g. 'iniciante'."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max results (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, muscle_group, equipment_type, level, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("exercises").select("id, name, muscle_group, equipment_type, suggested_level, short_description, image_url").order("name").limit(limit ?? 25);
    if (query) q = q.ilike("name", `%${query}%`);
    if (muscle_group) q = q.ilike("muscle_group", muscle_group);
    if (equipment_type) q = q.ilike("equipment_type", equipment_type);
    if (level) q = q.ilike("suggested_level", level);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { count: data?.length ?? 0, items: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_notifications_default = defineTool5({
  name: "list_notifications",
  title: "List my notifications",
  description: "List the signed-in user's TrainyLab notifications (workout approvals, expiry warnings, new students), newest first.",
  inputSchema: {
    only_unread: z3.boolean().optional().describe("Return only unread notifications."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_unread, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("notifications").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (only_unread) q = q.eq("read", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { count: data?.length ?? 0, items: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zyjvhralwvbbkloogrhj";
var mcp_default = defineMcp({
  name: "trainylab",
  title: "TrainyLab",
  version: "0.1.0",
  instructions: "Tools for TrainyLab, a training platform for personal trainers and their students. Use `get_my_profile` to know who the signed-in user is. Students can read their active workout plan with `get_workout_plan`. Personal trainers can list their students with `list_my_students` and read a student's plan by passing `student_user_id`. `search_exercises` browses the exercise catalog and `list_notifications` reads alerts. All data is scoped to the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_my_students_default, get_workout_plan_default, search_exercises_default, list_notifications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
